name: Ejecutar Ping Infinito

on:
  schedule:
    - cron: '*/5 * * * *'  # Esto ejecutará el script cada 5 minutos

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Instalar Python y dependencias
        run: |
          sudo apt update
          sudo apt install python3-pip
          pip3 install requests
      
      - name: Ejecutar el script de ping
        run: |
          python3 Test-Apps.py
